### ISSUE TITLE
Bug in chart  6.0.0 regarding DB port

### ISSUE THREAD

**Issue by klafbang** [codecentric/helm-charts#126] opened 2019-10-21 08:35 UTC
This morning, I upgraded from the latest 5.x.x release to 6.0.0.  This caused connection to the database to break.  I'm using an external postgres DB running on a non-standard port.

I was getting connection timeouts towards the database, despite logging in to the pod and successfully manually testing the connection using curl.

After double-checking the logs, I noticed this at the top of the pod logs:

> Added 'keycloak' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
> /opt/jboss/tools/docker-entrypoint.sh: line 138: append_port_db_addr: command not found
> =========================================================================

Since my DB is running on port 25060 instead of the default 5432, this could explain the issue.  As a work-around, I tried defining DB_ADDR manually (didn't work due to conflicts), but setting the dbHost to "host:port" worked.

This is of course just a workaround, but might be of use until the chart uses the value of dbPort again.

**Comment by unguiculus** [comment] 2019-10-25 07:37
Could you share your config? Did you set `keycloak.persistence.dbVendor` to `postgres`?

Setting up an external DB is documented here: https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/README.md#using-an-external-database

**Comment by klafbang** [comment] 2019-10-25 07:57
The workaround I had to use was

```
   dbHost: "host:25060"
   dbPort: "25060"
```

before 6.0.0, I just had

```
   dbHost: "host"
   dbPort: "25060"
```

**Comment by unguiculus** [comment] 2019-10-25 07:59
I just set up an external Postgres and can reproduce the issue. I'm looking into it now.

**Comment by unguiculus** [comment] 2019-10-25 08:12
I just tested `docker-entrypoint.sh` locally in isolation and it works as expected. I'm somewhat clueless at the moment why the function that does exist is not found.

https://github.com/keycloak/keycloak-containers/blob/master/server/tools/docker-entrypoint.sh#L146

**Comment by klafbang** [comment] 2019-10-25 08:38
Ah, makes sense.  I also looked up the script and was surprised.  Strange it has gone unreleased for several weeks…

**Comment by unguiculus** [comment] 2019-10-25 08:44
Closing this since it's a bug in the Docker image.

**Closed by unguiculus** 2019-10-25 08:44 UTC
