### ISSUE TITLE
[keycloak] helm3 tpl not expanding template

### ISSUE THREAD

**Issue by Rjvs** [codecentric/helm-charts#151] opened 2019-12-06 10:58 UTC
Using Helm 3.0 & 3.0.1, the tpl instruction doesn't appear to be expanding the template text, so the output looks like:

```
keycloak:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 10 }}
            matchExpressions:
 ```

**Comment by unguiculus** [comment] 2019-12-06 12:35
I cannot reproduce this. Works fine with Helm 3. In any case, it would be an issue with Helm, not chart chart, so I'm closing this.

**Closed by unguiculus** 2019-12-06 12:35 UTC
